### ISSUE TITLE
”怎么使用“可以再详细一点吗 小白不知道怎么运行 

### ISSUE THREAD

**Issue by JJUNLANG** [lighthookyu/gzhu-libbooking-master#1]

**Comment by lighthookyu** [comment]
使用腾讯云函数，设置好参数和触发器即可

**Comment by JJUNLANG** [comment]
![image](https://user-images.githubusercontent.com/112674337/221517992-7502bf05-b384-4185-8e4c-b7efcc38dad5.png)
config我都填好了运行的时候提示这个，啥意思怎么办

**Comment by JJUNLANG** [comment]
可以加个微信细说吗
