### ISSUE TITLE
云函数返回

### ISSUE THREAD

**Issue by JJUNLANG** [lighthookyu/gzhu-libbooking-master#4]
云函数返回这个，怎么解决
{

  "errorCode": 1,

  "errorMessage": "Traceback (most recent call last):\n  File \"/var/runtime/python2/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python2/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/user/main.py\", line 6, in &lt;module;&gt;\n    from Crypto.Cipher import PKCS1_v1_5 as Cipher_pksc1_v1_5\nImportError: No module named Crypto.Cipher",

  "requestId": "efa631d0-95aa-425d-a23b-fa5ca7839e9e",

  "statusCode": 443

**Comment by lighthookyu** [comment]
在云函数的终端安装下requirments.txt里面的依赖包

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："JJUNLANG ***@***.***&gt;;
发送时间：2023年2月28日(星期二) 晚上8:54
收件人："lighthookyu/gzhu-libbooking-master" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lighthookyu/gzhu-libbooking-master] 云函数返回 (Issue #4)
-----------------------------------

 

 
云函数返回这个，怎么解决
 {
 
"errorCode": 1,
 
"errorMessage": "Traceback (most recent call last):\n  File "/var/runtime/python2/bootstrap.py", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(".", 1)[0], func)\n  File "/var/runtime/python2/bootstrap.py", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File "/var/user/main.py", line 6, in <module;&gt;\n    from Crypto.Cipher import PKCS1_v1_5 as Cipher_pksc1_v1_5\nImportError: No module named Crypto.Cipher",
 
"requestId": "efa631d0-95aa-425d-a23b-fa5ca7839e9e",
 
"statusCode": 443

**Comment by JJUNLANG** [comment]
哪里有requirments.txt

**Comment by JJUNLANG** [comment]
我安装了requests和Crypto，然后还是提示我 No module named Crypto.Cipher", 发现Crypto文件下没有Crypto.Ciphe，我就继续百度需要我 pip install pycryptodome，但是我安装不了这个pycryptodome，提示：Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality. 我用pip3 install pycryptodome 提示：Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by lighthookyu** [comment]
重做一个新的py3.7的云函数，装requests和pycryptodome。


crypto不用装，那个库太老了

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："JJUNLANG ***@***.***&gt;;
发送时间：2023年3月1日(星期三) 中午1:15
收件人："lighthookyu/gzhu-libbooking-master" ***@***.***&gt;;
抄送："lighthookyu ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lighthookyu/gzhu-libbooking-master] 云函数返回 (Issue #4)
-----------------------------------

 

 
我安装了requests和Crypto，然后还是提示我 No module named Crypto.Cipher", 发现Crypto文件下没有Crypto.Ciphe，我就继续百度需要我 pip install pycryptodome，但是我安装不了这个pycryptodome，提示：Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality. 我用pip3 install pycryptodome 提示：Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

**Comment by JJUNLANG** [comment]
执行方法要改吗
![image](https://user-images.githubusercontent.com/112674337/222054073-996fa2e3-18dd-4e45-9cbf-5f88eb75a5a3.png)

**Comment by JJUNLANG** [comment]
安装完两个库测试结果如下，然后要怎么处理
![image](https://user-images.githubusercontent.com/112674337/222054189-86fff1ea-d02b-4d99-bba1-b18e2d804d67.png)

**Comment by JJUNLANG** [comment]
好像可以了！谢谢老哥 我还想问一下可以是不是只能预约1楼的，如果想要预约其他楼层的，代码需要怎么改呢

**Comment by lighthookyu** [comment]
这个请自行研究哈~

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："JJUNLANG ***@***.***&gt;;
发送时间：2023年3月1日(星期三) 中午1:48
收件人："lighthookyu/gzhu-libbooking-master" ***@***.***&gt;;
抄送："lighthookyu ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lighthookyu/gzhu-libbooking-master] 云函数返回 (Issue #4)
-----------------------------------

 

 
好像可以了！谢谢老哥 我还想问一下可以是不是只能预约1楼的，如果想要预约其他楼层的，代码需要怎么改呢
