### ISSUE TITLE
关于加密的一点疑惑

### ISSUE THREAD

**Issue by BitSim** [lighthookyu/gzhu-libbooking-master#7]
你好，我想请问是怎么发现publickey的，加密工作怎么知道是那样做😶

**Comment by lighthookyu** [comment]
经验

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："None ***@***.***&gt;;
发送时间：2023年6月2日(星期五) 晚上6:41
收件人："lighthookyu/gzhu-libbooking-master" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[lighthookyu/gzhu-libbooking-master] 关于加密的一点疑惑 (Issue #7)
-----------------------------------

 

 
你好，我想请问是怎么发现publickey的，加密工作怎么知道是那样做😶

**Comment by lighthookyu** [comment]
一般来说，直接F12抓取就可以了。只是需要多去尝试

**Comment by BitSim** [comment]
> 一般来说，直接F12抓取就可以了。只是需要多去尝试

那大佬是怎么知道对应的加密过程，是通过分析js中的内容吗🐼
查看源码发现这一行
public_key = '-----BEGIN PUBLIC KEY-----\n' + publicKey + '\n-----END PUBLIC KEY-----'
惊呆了，这个key格式是怎么发现的🐼

**Comment by lighthookyu** [comment]
非主流互联网公司的算法基本是外包系统附带的，善用f12debug

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："None ***@***.***&gt;;
发送时间：2023年6月5日(星期一) 中午12:41
收件人："lighthookyu/gzhu-libbooking-master" ***@***.***&gt;;
抄送："lighthookyu ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lighthookyu/gzhu-libbooking-master] 关于加密的一点疑惑 (Issue #7)
-----------------------------------

 

  
一般来说，直接F12抓取就可以了。只是需要多去尝试
  
那大佬是怎么知道对应的加密过程，是通过分析js中的内容吗🐼
